version: "3.9"
services:
  fastapi:
    build: .
    command: uvicorn hello:app --host 0.0.0.0 --reload --port 5000
    environment:      
      - FASTAPI_APP=hello.py
      - FASTAPI_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - ./:/root